#!/usr/bin/env python3
"""Generate both Herdr Shell clients' design tokens from shell/tokens.json.

  python3 shell/gen_tokens.py           write the generated files
  python3 shell/gen_tokens.py --check   exit 1 when the clients have drifted

One JSON file, plain code generation: Swift gets compile-time constants with no
resource loading, the web client gets CSS variables and an xterm theme module.
--check fails when:
  - a generated file differs from what the JSON produces (hand edit or stale);
  - the Mac app's effective stock-theme colors, computed by compiling Theme.swift
    with the generated constants, differ from the JSON (Theme.swift overriding a token);
  - the Windows client spells a color literal outside the generated files, or uses
    a --shell-* variable the generator does not define;
  - a light-mode text color is under WCAG 4.5:1 on any light chrome surface.
Stdlib only.
"""
import json
import pathlib
import re
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / "shell/tokens.json"
MAC_DIR = ROOT / "macos/HerdrShell/Sources/HerdrShell"
MAC_OUT = MAC_DIR / "ShellTokens.swift"
WEB_DIR = ROOT / "windows/HerdrShell/app/src"
CSS_OUT = WEB_DIR / "tokens.css"
TS_OUT = WEB_DIR / "tokens.ts"
HEADER = "Generated by shell/gen_tokens.py from shell/tokens.json. Do not edit; edit the JSON and rerun."

CHROME = ["windowBg", "panel", "line", "sel", "ink", "mute", "orch", "lane", "wf", "ok", "warn",
          "cap", "hover", "split", "field", "faint", "accent", "bad"]
# Web names for chrome tokens; the rest are kebab-cased Mac names.
CSS_NAME = {"windowBg": "bg", "panel": "surface", "ink": "text", "mute": "muted", "sel": "selection"}
XTERM_ANSI = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"]


def kebab(s):
    return re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", s).lower()


def num(v):
    return ("%g" % v)


def hex6(v):
    v = v.lstrip("#")
    if not re.fullmatch(r"[0-9A-Fa-f]{6}", v):
        raise SystemExit(f"bad color {v!r}")
    return v.upper()


def load():
    t = json.loads(SRC.read_text())
    for mode in ("dark", "light"):
        missing = [k for k in CHROME if k not in t["color"][mode]]
        extra = [k for k in t["color"][mode] if k not in CHROME]
        if missing or extra:
            raise SystemExit(f"color.{mode}: missing {missing} extra {extra}")
    return t


def swift(t):
    out = [f"// {HEADER}", "import CoreGraphics", "", "extension ChromePalette {"]
    for mode in ("dark", "light"):
        c = t["color"][mode]
        args = ", ".join(f"{k}: 0x{hex6(c[k])}" for k in CHROME)
        out.append(f"    static let {mode} = ChromePalette({args})")
    out += ["}", "", "extension TerminalTheme {"]
    for mode in ("dark", "light"):
        term = t["terminal"][mode]
        out.append(f"    static let fallback{mode.capitalize()}: (bg: UInt32, fg: UInt32) = "
                   f"(0x{hex6(term['background'])}, 0x{hex6(term['foreground'])})")
    out.append("}")
    for enum, key in (("ShellType", "type"), ("ShellSpace", "space"), ("ShellRadius", "radius")):
        out += ["", f"enum {enum} {{"]
        for k, v in t[key].items():
            if not k.startswith("_"):
                out.append(f"    static let {k}: CGFloat = {num(v)}")
        out.append("}")
    face = t["face"]
    out += ["", "enum ShellFace {"]
    for k, v in face.items():
        if k.startswith("_") or k == "tints":
            continue
        out.append(f"    static let {k}: CGFloat = {num(v)}")
    out.append("    static let tints: [UInt32] = [" + ", ".join(f"0x{hex6(c)}" for c in face["tints"]) + "]")
    out.append("}")
    return "\n".join(out) + "\n"


def css_colors(t, mode):
    c = t["color"][mode]
    sb = t["scrollbar"][mode]
    lines = [f"  --shell-{CSS_NAME.get(k, kebab(k))}: #{hex6(c[k])};" for k in CHROME]
    lines.append(f"  --shell-scrim: #{hex6(c['windowBg'])}EE;")
    lines.append(f"  --shell-scroll-thumb: #{sb['thumb'].lstrip('#').upper()};")
    lines.append(f"  --shell-scroll-thumb-hover: #{sb['thumbHover'].lstrip('#').upper()};")
    term = t["terminal"][mode]
    lines.append(f"  --shell-terminal-bg: #{hex6(term['background'])};")
    lines.append(f"  --shell-terminal-fg: #{hex6(term['foreground'])};")
    return lines


def css(t):
    sb = t["scrollbar"]
    metrics = [f"  --shell-font-ui: {t['font']['ui']['windows']};",
               f"  --shell-font-mono: {t['font']['mono']['windows']};"]
    for group in ("type", "space", "radius"):
        for k, v in t[group].items():
            if k.startswith("_"):
                continue
            unit = "px"
            metrics.append(f"  --shell-{group}-{kebab(k)}: {num(v)}{unit};")
    for k, v in t["face"].items():
        if k.startswith("_"):
            continue
        if k == "tints":
            metrics += [f"  --shell-face-tint-{i}: #{hex6(c)};" for i, c in enumerate(v)]
        else:
            metrics.append(f"  --shell-face-{kebab(k)}: {num(v)}{'' if k.startswith('tintOpacity') else 'px'};")
    out = [f"/* {HEADER} */",
           "/* Dark is the default; src/theme.ts sets data-theme from the Windows app theme. */",
           ':root, :root[data-theme="dark"] {', "  color-scheme: dark;", *css_colors(t, "dark"), "}",
           ':root[data-theme="light"] {', "  color-scheme: light;", *css_colors(t, "light"), "}",
           ":root {", *metrics, "}",
           "/* Overlay-style scrollbars, as on macOS: no track or arrows, a thin rounded thumb",
           "   that shows while the pointer is over the scroller. */",
           f"::-webkit-scrollbar {{ width: {sb['size']}px; height: {sb['size']}px; background: transparent; }}",
           "::-webkit-scrollbar-track, ::-webkit-scrollbar-corner { background: transparent; }",
           "::-webkit-scrollbar-button { display: none; }",
           f"::-webkit-scrollbar-thumb {{ background-color: transparent; border: {sb['thumbInset']}px solid transparent; "
           f"background-clip: content-box; border-radius: {sb['size']}px; min-height: {sb['thumbMinLength']}px; "
           f"min-width: {sb['thumbMinLength']}px; }}",
           ":hover::-webkit-scrollbar-thumb { background-color: var(--shell-scroll-thumb); }",
           "::-webkit-scrollbar-thumb:hover, ::-webkit-scrollbar-thumb:active { background-color: var(--shell-scroll-thumb-hover); }"]
    return "\n".join(out) + "\n"


def ts(t):
    out = [f"// {HEADER}", 'import type { ITheme } from "@xterm/xterm";', "",
           'export type TokenMode = "light" | "dark";', "",
           "/** The default Ghostty theme pair the Mac shell loads, as xterm themes. */",
           "export const terminalThemes: Record<TokenMode, ITheme> = {"]
    for mode in ("dark", "light"):
        term = t["terminal"][mode]
        pal = [f"#{hex6(c)}" for c in term["palette"]]
        fields = [f'background: "#{hex6(term["background"])}"', f'foreground: "#{hex6(term["foreground"])}"',
                  f'cursor: "#{hex6(term["cursor"])}"', f'cursorAccent: "#{hex6(term["cursorText"])}"',
                  f'selectionBackground: "#{hex6(term["selectionBackground"])}"',
                  f'selectionForeground: "#{hex6(term["selectionForeground"])}"']
        fields += [f'{n}: "{pal[i]}"' for i, n in enumerate(XTERM_ANSI)]
        fields += [f'bright{n[0].upper()}{n[1:]}: "{pal[i + 8]}"' for i, n in enumerate(XTERM_ANSI)]
        out.append(f"  {mode}: {{ {', '.join(fields)} }},")
    out += ["};", "",
            f"export const terminalFont = {{ family: {json.dumps(t['font']['mono']['windows'])}, size: {num(t['type']['terminal'])} }};"]
    return "\n".join(out) + "\n"


def outputs(t):
    return {MAC_OUT: swift(t), CSS_OUT: css(t), TS_OUT: ts(t)}


MAC_DRIVER = """
import Foundation
func log(_ s: String) {}
let tt = TerminalTheme(dark: "Catppuccin Mocha", light: "SF Paper",
                       darkColors: TerminalTheme.fallbackDark, lightColors: TerminalTheme.fallbackLight)
var all: [String: [String: String]] = [:]
for m in Mode.allCases {
    let t = ThemeStore.tokens(for: m, terminal: tt)
    var d: [String: String] = [:]
    for n in CommandLine.arguments.dropFirst() { d[n] = ThemeStore.hex(t.chrome.value(n)!) }
    d["terminalBg"] = ThemeStore.hex(t.terminalBg)
    d["terminalFg"] = ThemeStore.hex(t.terminalFg)
    all[m.rawValue] = d
}
print(String(decoding: try! JSONSerialization.data(withJSONObject: all, options: [.sortedKeys]), as: UTF8.self))
"""


def mac_effective():
    """Compile the app's Theme.swift with the generated constants and dump the stock tokens."""
    with tempfile.TemporaryDirectory(prefix="shell-tokens-") as d:
        drv = pathlib.Path(d) / "main.swift"
        drv.write_text(MAC_DRIVER)
        exe = pathlib.Path(d) / "dump"
        subprocess.run(["swiftc", str(MAC_DIR / "Theme.swift"), str(MAC_OUT), str(drv), "-o", str(exe)],
                       check=True, capture_output=True, text=True)
        return json.loads(subprocess.check_output([str(exe), *CHROME], text=True))


COLOR_LITERAL = re.compile(r"#[0-9A-Fa-f]{3,8}\b|\b(?:rgba?|hsla?|hwb|lab|lch|oklab|oklch|color)\(", re.I)
NAMED = ("aliceblue antiquewhite aqua aquamarine azure beige bisque black blanchedalmond blue blueviolet brown "
         "burlywood cadetblue chartreuse chocolate coral cornflowerblue cornsilk crimson cyan darkblue darkcyan "
         "darkgoldenrod darkgray darkgreen darkgrey darkkhaki darkmagenta darkolivegreen darkorange darkorchid "
         "darkred darksalmon darkseagreen darkslateblue darkslategray darkslategrey darkturquoise darkviolet "
         "deeppink deepskyblue dimgray dimgrey dodgerblue firebrick floralwhite forestgreen fuchsia gainsboro "
         "ghostwhite gold goldenrod gray green greenyellow grey honeydew hotpink indianred indigo ivory khaki "
         "lavender lavenderblush lawngreen lemonchiffon lightblue lightcoral lightcyan lightgoldenrodyellow "
         "lightgray lightgreen lightgrey lightpink lightsalmon lightseagreen lightskyblue lightslategray "
         "lightslategrey lightsteelblue lightyellow lime limegreen linen magenta maroon mediumaquamarine "
         "mediumblue mediumorchid mediumpurple mediumseagreen mediumslateblue mediumspringgreen mediumturquoise "
         "mediumvioletred midnightblue mintcream mistyrose moccasin navajowhite navy oldlace olive olivedrab "
         "orange orangered orchid palegoldenrod palegreen paleturquoise palevioletred papayawhip peachpuff peru "
         "pink plum powderblue purple rebeccapurple red rosybrown royalblue saddlebrown salmon sandybrown "
         "seagreen seashell sienna silver skyblue slateblue slategray slategrey snow springgreen steelblue tan "
         "teal thistle tomato turquoise violet wheat white whitesmoke yellow yellowgreen "
         "canvas canvastext linktext visitedtext activetext buttonface buttontext buttonborder field fieldtext "
         "highlight highlighttext selecteditem selecteditemtext mark marktext graytext accentcolor accentcolortext")
NAMED_RE = r"(?<![\w-])(?:" + "|".join(NAMED.split()) + r")(?![\w-])"
# Properties that take a color: a named color in their value is a literal.
# Properties that take a color: a named color in their value is a literal. Declarations may span lines.
CSS_COLOR_DECL = re.compile(r"(?:^|[;{\s])((?:background|border|outline|text-decoration|column-rule)[\w-]*|color|fill|stroke|"
                            r"caret-color|accent-color|scrollbar-color|box-shadow|text-shadow)\s*:([^;}]*)", re.I | re.M)
TS_COLOR_PROP = re.compile(r"[\"']?\b(?:color|background\w*|border\w*|outline\w*|fill|stroke|boxShadow|textShadow|caretColor|"
                           r"accentColor|scrollbarColor|textDecorationColor|cursor\w*|selection\w*)[\"']?\s*:\s*[\"'`]([^\"'`]*)[\"'`]")
VAR_USE = re.compile(r"var\(\s*(--shell-[a-z0-9-]+)")
VAR_DEF = re.compile(r"(?:^|[;{\s])(--shell-[a-z0-9-]+)\s*:", re.M)


def strip_comments(text, css):
    """Blank out comments, keeping line numbers. TS line comments need a non-colon before // (not urls)."""
    pattern = r"/\*.*?\*/" if css else r"/\*.*?\*/|(?<![:\\])//[^\n]*"
    return re.sub(pattern, lambda m: re.sub(r"[^\n]", " ", m.group(0)), text, flags=re.S)


def web_lint(generated_css):
    defined = set(VAR_DEF.findall(strip_comments(generated_css, True)))
    problems = []
    for f in sorted(WEB_DIR.rglob("*")):
        if f.suffix not in (".css", ".ts", ".tsx") or f in (CSS_OUT, TS_OUT) or ".test." in f.name:
            continue
        css = f.suffix == ".css"
        text = strip_comments(f.read_text(), css)
        # Only CSS declares variables; a string in TS that looks like one defines nothing.
        local = set(VAR_DEF.findall(text)) if css else set()
        rel = f.relative_to(ROOT)
        found = [(m.start(), m.group(0)) for m in COLOR_LITERAL.finditer(text)]
        decls = CSS_COLOR_DECL if css else TS_COLOR_PROP
        group = 2 if css else 1
        for d in decls.finditer(text):
            # url(...) and quoted strings in a CSS value are names, not colors ("red.svg").
            value = d.group(group) if not css else re.sub(r"url\([^)]*\)|\"[^\"]*\"|'[^']*'",
                                                         lambda m: " " * len(m.group(0)), d.group(group))
            found += [(d.start(group) + m.start(), m.group(0)) for m in re.finditer(NAMED_RE, value, re.I)]
        for pos, lit in sorted(found):
            problems.append(f"{rel}:{text.count(chr(10), 0, pos) + 1}: color literal {lit!r}; use a --shell-* token")
        for m in VAR_USE.finditer(text):
            if m.group(1) not in defined and m.group(1) not in local:
                problems.append(f"{rel}:{text.count(chr(10), 0, m.start()) + 1}: {m.group(1)} is not a generated token")
    return problems


# Text colors and the chrome surfaces they sit on (Alex's parity ask, 2026-10-06: light text at
# least 4.5:1). Dark is not held yet: its mute and faint come from the Mocha-derived palette.
TEXT = ("ink", "mute", "faint", "orch", "lane", "wf", "ok", "warn", "accent", "bad")
SURFACES = ("windowBg", "panel", "sel", "hover", "cap", "field")


def contrast(a, b):
    def lum(v):
        c = [int(hex6(v)[i:i + 2], 16) / 255 for i in (0, 2, 4)]
        c = [x / 12.92 if x <= 0.03928 else ((x + 0.055) / 1.055) ** 2.4 for x in c]
        return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2]
    hi, lo = sorted((lum(a), lum(b)), reverse=True)
    return (hi + 0.05) / (lo + 0.05)


def low_contrast(t):
    c = t["color"]["light"]
    return [f"light {fg} {c[fg]} on {bg} {c[bg]} is {contrast(c[fg], c[bg]):.2f}:1, under 4.5:1"
            for fg in TEXT for bg in SURFACES if contrast(c[fg], c[bg]) < 4.5]


def check(t):
    failures = []
    for path, text in outputs(t).items():
        rel = path.relative_to(ROOT)
        if not path.exists() or path.read_text() != text:
            failures.append(f"{rel} is stale; run python3 shell/gen_tokens.py")
        else:
            print(f"PASS {rel} matches shell/tokens.json")
    if not failures:
        eff = mac_effective()
        miss = []
        for mode in ("dark", "light"):
            want = {k: "#" + hex6(v) for k, v in t["color"][mode].items()}
            want["terminalBg"] = "#" + hex6(t["terminal"][mode]["background"])
            want["terminalFg"] = "#" + hex6(t["terminal"][mode]["foreground"])
            for k, v in want.items():
                if eff[mode].get(k) != v:
                    miss.append(f"mac {mode}.{k} = {eff[mode].get(k)} but tokens.json says {v}")
        if miss:
            failures += miss
        else:
            print("PASS mac effective stock colors equal tokens.json (dark, light)")
    low = low_contrast(t)
    if low:
        failures += low
    else:
        print("PASS light text colors are at least 4.5:1 on every light surface")
    lint = web_lint(outputs(t)[CSS_OUT])
    if lint:
        failures += lint
    else:
        print("PASS windows client uses only generated color tokens")
    for f in failures:
        print("FAIL " + f)
    return 1 if failures else 0


def main():
    t = load()
    if "--check" in sys.argv[1:]:
        sys.exit(check(t))
    for path, text in outputs(t).items():
        path.write_text(text)
        print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
