#!/usr/bin/env python3
"""Generate both Herdr Shell clients' design tokens from shell/tokens.json.

  python3 shell/gen_tokens.py           write the generated files
  python3 shell/gen_tokens.py --check   exit 1 when the clients have drifted

One JSON file, plain code generation: Swift gets compile-time constants with no
resource loading, the web client gets CSS variables and an xterm theme module.
--check fails when:
  - a generated file differs from what the JSON produces (hand edit or stale);
  - the Mac app's effective stock-theme colors, computed by compiling Theme.swift
    with the generated constants, differ from the JSON (Theme.swift overriding a token);
  - the Windows client spells a color literal outside the generated files, or uses
    a --shell-* variable the generator does not define.
Stdlib only.
"""
import json
import pathlib
import re
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / "shell/tokens.json"
MAC_DIR = ROOT / "macos/HerdrShell/Sources/HerdrShell"
MAC_OUT = MAC_DIR / "ShellTokens.swift"
WEB_DIR = ROOT / "windows/HerdrShell/app/src"
CSS_OUT = WEB_DIR / "tokens.css"
TS_OUT = WEB_DIR / "tokens.ts"
HEADER = "Generated by shell/gen_tokens.py from shell/tokens.json. Do not edit; edit the JSON and rerun."

CHROME = ["windowBg", "panel", "line", "sel", "ink", "mute", "orch", "lane", "wf", "ok", "warn",
          "cap", "hover", "split", "field", "faint", "accent", "bad"]
# Web names for chrome tokens; the rest are kebab-cased Mac names.
CSS_NAME = {"windowBg": "bg", "panel": "surface", "ink": "text", "mute": "muted", "sel": "selection"}
XTERM_ANSI = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"]


def kebab(s):
    return re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", s).lower()


def num(v):
    return ("%g" % v)


def hex6(v):
    v = v.lstrip("#")
    if not re.fullmatch(r"[0-9A-Fa-f]{6}", v):
        raise SystemExit(f"bad color {v!r}")
    return v.upper()


def load():
    t = json.loads(SRC.read_text())
    for mode in ("dark", "light"):
        missing = [k for k in CHROME if k not in t["color"][mode]]
        extra = [k for k in t["color"][mode] if k not in CHROME]
        if missing or extra:
            raise SystemExit(f"color.{mode}: missing {missing} extra {extra}")
    return t


def swift(t):
    out = [f"// {HEADER}", "import CoreGraphics", "", "extension ChromePalette {"]
    for mode in ("dark", "light"):
        c = t["color"][mode]
        args = ", ".join(f"{k}: 0x{hex6(c[k])}" for k in CHROME)
        out.append(f"    static let {mode} = ChromePalette({args})")
    out += ["}", "", "extension TerminalTheme {"]
    for mode in ("dark", "light"):
        term = t["terminal"][mode]
        out.append(f"    static let fallback{mode.capitalize()}: (bg: UInt32, fg: UInt32) = "
                   f"(0x{hex6(term['background'])}, 0x{hex6(term['foreground'])})")
    out.append("}")
    for enum, key in (("ShellType", "type"), ("ShellSpace", "space"), ("ShellRadius", "radius")):
        out += ["", f"enum {enum} {{"]
        for k, v in t[key].items():
            if not k.startswith("_"):
                out.append(f"    static let {k}: CGFloat = {num(v)}")
        out.append("}")
    return "\n".join(out) + "\n"


def css_colors(t, mode):
    c = t["color"][mode]
    sb = t["scrollbar"][mode]
    lines = [f"  --shell-{CSS_NAME.get(k, kebab(k))}: #{hex6(c[k])};" for k in CHROME]
    lines.append(f"  --shell-scrim: #{hex6(c['windowBg'])}EE;")
    lines.append(f"  --shell-scroll-thumb: #{sb['thumb'].lstrip('#').upper()};")
    lines.append(f"  --shell-scroll-thumb-hover: #{sb['thumbHover'].lstrip('#').upper()};")
    term = t["terminal"][mode]
    lines.append(f"  --shell-terminal-bg: #{hex6(term['background'])};")
    lines.append(f"  --shell-terminal-fg: #{hex6(term['foreground'])};")
    return lines


def css(t):
    sb = t["scrollbar"]
    metrics = [f"  --shell-font-ui: {t['font']['ui']['windows']};",
               f"  --shell-font-mono: {t['font']['mono']['windows']};"]
    for group in ("type", "space", "radius"):
        for k, v in t[group].items():
            if k.startswith("_"):
                continue
            unit = "px"
            metrics.append(f"  --shell-{group}-{kebab(k)}: {num(v)}{unit};")
    out = [f"/* {HEADER} */",
           "/* Dark is the default; src/theme.ts sets data-theme from the Windows app theme. */",
           ':root, :root[data-theme="dark"] {', "  color-scheme: dark;", *css_colors(t, "dark"), "}",
           ':root[data-theme="light"] {', "  color-scheme: light;", *css_colors(t, "light"), "}",
           ":root {", *metrics, "}",
           "/* Overlay-style scrollbars, as on macOS: no track or arrows, a thin rounded thumb",
           "   that shows while the pointer is over the scroller. */",
           f"::-webkit-scrollbar {{ width: {sb['size']}px; height: {sb['size']}px; background: transparent; }}",
           "::-webkit-scrollbar-track, ::-webkit-scrollbar-corner { background: transparent; }",
           "::-webkit-scrollbar-button { display: none; }",
           f"::-webkit-scrollbar-thumb {{ background-color: transparent; border: {sb['thumbInset']}px solid transparent; "
           f"background-clip: content-box; border-radius: {sb['size']}px; min-height: {sb['thumbMinLength']}px; "
           f"min-width: {sb['thumbMinLength']}px; }}",
           ":hover::-webkit-scrollbar-thumb { background-color: var(--shell-scroll-thumb); }",
           "::-webkit-scrollbar-thumb:hover, ::-webkit-scrollbar-thumb:active { background-color: var(--shell-scroll-thumb-hover); }"]
    return "\n".join(out) + "\n"


def ts(t):
    out = [f"// {HEADER}", 'import type { ITheme } from "@xterm/xterm";', "",
           'export type TokenMode = "light" | "dark";', "",
           "/** The default Ghostty theme pair the Mac shell loads, as xterm themes. */",
           "export const terminalThemes: Record<TokenMode, ITheme> = {"]
    for mode in ("dark", "light"):
        term = t["terminal"][mode]
        pal = [f"#{hex6(c)}" for c in term["palette"]]
        fields = [f'background: "#{hex6(term["background"])}"', f'foreground: "#{hex6(term["foreground"])}"',
                  f'cursor: "#{hex6(term["cursor"])}"', f'cursorAccent: "#{hex6(term["cursorText"])}"',
                  f'selectionBackground: "#{hex6(term["selectionBackground"])}"',
                  f'selectionForeground: "#{hex6(term["selectionForeground"])}"']
        fields += [f'{n}: "{pal[i]}"' for i, n in enumerate(XTERM_ANSI)]
        fields += [f'bright{n[0].upper()}{n[1:]}: "{pal[i + 8]}"' for i, n in enumerate(XTERM_ANSI)]
        out.append(f"  {mode}: {{ {', '.join(fields)} }},")
    out += ["};", "",
            f"export const terminalFont = {{ family: {json.dumps(t['font']['mono']['windows'])}, size: {num(t['type']['terminal'])} }};"]
    return "\n".join(out) + "\n"


def outputs(t):
    return {MAC_OUT: swift(t), CSS_OUT: css(t), TS_OUT: ts(t)}


MAC_DRIVER = """
import Foundation
func log(_ s: String) {}
let tt = TerminalTheme(dark: "Catppuccin Mocha", light: "SF Paper",
                       darkColors: TerminalTheme.fallbackDark, lightColors: TerminalTheme.fallbackLight)
var all: [String: [String: String]] = [:]
for m in Mode.allCases {
    let t = ThemeStore.tokens(for: m, terminal: tt)
    var d: [String: String] = [:]
    for n in CommandLine.arguments.dropFirst() { d[n] = ThemeStore.hex(t.chrome.value(n)!) }
    d["terminalBg"] = ThemeStore.hex(t.terminalBg)
    d["terminalFg"] = ThemeStore.hex(t.terminalFg)
    all[m.rawValue] = d
}
print(String(decoding: try! JSONSerialization.data(withJSONObject: all, options: [.sortedKeys]), as: UTF8.self))
"""


def mac_effective():
    """Compile the app's Theme.swift with the generated constants and dump the stock tokens."""
    with tempfile.TemporaryDirectory(prefix="shell-tokens-") as d:
        drv = pathlib.Path(d) / "main.swift"
        drv.write_text(MAC_DRIVER)
        exe = pathlib.Path(d) / "dump"
        subprocess.run(["swiftc", str(MAC_DIR / "Theme.swift"), str(MAC_OUT), str(drv), "-o", str(exe)],
                       check=True, capture_output=True, text=True)
        return json.loads(subprocess.check_output([str(exe), *CHROME], text=True))


COLOR_LITERAL = re.compile(r"#[0-9A-Fa-f]{3,8}\b|\brgba?\(|\bhsla?\(")
VAR_USE = re.compile(r"var\(\s*(--shell-[a-z0-9-]+)")
VAR_DEF = re.compile(r"(--shell-[a-z0-9-]+)\s*:")


def web_lint(generated_css):
    defined = set(VAR_DEF.findall(generated_css))
    problems = []
    for f in sorted(WEB_DIR.rglob("*")):
        if f.suffix not in (".css", ".ts", ".tsx") or f in (CSS_OUT, TS_OUT) or f.name.endswith(".test.ts"):
            continue
        for n, line in enumerate(f.read_text().splitlines(), 1):
            code = line.split("//")[0] if f.suffix != ".css" else line
            for m in COLOR_LITERAL.finditer(code):
                problems.append(f"{f.relative_to(ROOT)}:{n}: color literal {m.group(0)!r}; use a --shell-* token")
            for name in VAR_USE.findall(line):
                if name not in defined and not re.search(re.escape(name) + r"\s*:", f.read_text()):
                    problems.append(f"{f.relative_to(ROOT)}:{n}: {name} is not a generated token")
    return problems


def check(t):
    failures = []
    for path, text in outputs(t).items():
        rel = path.relative_to(ROOT)
        if not path.exists() or path.read_text() != text:
            failures.append(f"{rel} is stale; run python3 shell/gen_tokens.py")
        else:
            print(f"PASS {rel} matches shell/tokens.json")
    if not failures:
        eff = mac_effective()
        miss = []
        for mode in ("dark", "light"):
            want = {k: "#" + hex6(v) for k, v in t["color"][mode].items()}
            want["terminalBg"] = "#" + hex6(t["terminal"][mode]["background"])
            want["terminalFg"] = "#" + hex6(t["terminal"][mode]["foreground"])
            for k, v in want.items():
                if eff[mode].get(k) != v:
                    miss.append(f"mac {mode}.{k} = {eff[mode].get(k)} but tokens.json says {v}")
        if miss:
            failures += miss
        else:
            print("PASS mac effective stock colors equal tokens.json (dark, light)")
    lint = web_lint(outputs(t)[CSS_OUT])
    if lint:
        failures += lint
    else:
        print("PASS windows client uses only generated color tokens")
    for f in failures:
        print("FAIL " + f)
    return 1 if failures else 0


def main():
    t = load()
    if "--check" in sys.argv[1:]:
        sys.exit(check(t))
    for path, text in outputs(t).items():
        path.write_text(text)
        print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
