// Generated by shell/gen_tokens.py from shell/tokens.json. Do not edit; edit the JSON and rerun.
import CoreGraphics

extension ChromePalette {
    static let dark = ChromePalette(windowBg: 0x1E1E2E, panel: 0x16171B, line: 0x26272D, sel: 0x1F2230, ink: 0xE6E6EA, mute: 0x8B8C94, orch: 0x5AA9FF, lane: 0xA3AAFF, wf: 0x5CC8C8, ok: 0x4CD27A, warn: 0xF2B04C, cap: 0x181825, hover: 0x222232, split: 0x3A3B4E, field: 0x24253A, faint: 0x6C7086, accent: 0x89B4FA, bad: 0xF38BA8)
    static let light = ChromePalette(windowBg: 0xFFFFFF, panel: 0xF3F4F6, line: 0xD5D8DE, sel: 0xE1E6F2, ink: 0x1F2328, mute: 0x565C66, orch: 0x0A5FC4, lane: 0x4A4FC7, wf: 0x0B6E74, ok: 0x17692F, warn: 0x8A5300, cap: 0xF3F3F3, hover: 0xF0F0ED, split: 0xDFDFDF, field: 0xF2F2EF, faint: 0x63666B, accent: 0x0963CE, bad: 0xC7212C)
}

extension TerminalTheme {
    static let fallbackDark: (bg: UInt32, fg: UInt32) = (0x1E1E2E, 0xCDD6F4)
    static let fallbackLight: (bg: UInt32, fg: UInt32) = (0xFFFFFF, 0x3A3A38)
}

enum ShellType {
    static let sectionLabel: CGFloat = 10.5
    static let sectionTracking: CGFloat = 0.4
    static let rowTitle: CGFloat = 12.5
    static let rowTrailing: CGFloat = 10.5
    static let glyph: CGFloat = 10
    static let caption: CGFloat = 11.5
    static let small: CGFloat = 12.5
    static let body: CGFloat = 14
    static let code: CGFloat = 12.5
    static let terminal: CGFloat = 13.5
    static let switcherQuery: CGFloat = 16
    static let switcherRow: CGFloat = 13
    static let switcherMeta: CGFloat = 11
    static let chatH1: CGFloat = 19
    static let chatH2: CGFloat = 16.5
    static let chatH3: CGFloat = 14.5
}

enum ShellSpace {
    static let sidebarWidth: CGFloat = 300
    static let rowHeight: CGFloat = 23
    static let rowPadX: CGFloat = 4
    static let paneCapHeight: CGFloat = 36
    static let chatColumn: CGFloat = 760
    static let chatGutter: CGFloat = 28
    static let chatItemGap: CGFloat = 18
    static let chatBlockGap: CGFloat = 12
    static let toolRow: CGFloat = 22
    static let docWidth: CGFloat = 420
    static let docMinWidth: CGFloat = 320
    static let switcherWidth: CGFloat = 560
    static let terminalPadX: CGFloat = 8
    static let terminalPadY: CGFloat = 6
}

enum ShellRadius {
    static let row: CGFloat = 4
    static let control: CGFloat = 6
    static let code: CGFloat = 8
    static let overlay: CGFloat = 10
    static let composer: CGFloat = 14
    static let bubble: CGFloat = 16
}

enum ShellFace {
    static let size: CGFloat = 16
    static let dot: CGFloat = 6
    static let dotGap: CGFloat = 1.5
    static let dotOffset: CGFloat = 1
    static let ring: CGFloat = 0.5
    static let initial: CGFloat = 9.5
    static let tintOpacityLight: CGFloat = 0.24
    static let tintOpacityDark: CGFloat = 0.32
    static let tints: [UInt32] = [0x8B5E3C, 0xE8483F, 0xF08A24, 0xF0B429, 0x3ECF8E, 0x2FBFA0, 0x3B93F0, 0x8B5CF6, 0xE152B0]
}
