// Generated by shell/gen_tokens.py from shell/tokens.json. Do not edit; edit the JSON and rerun.
import CoreGraphics

extension ChromePalette {
    static let dark = ChromePalette(windowBg: 0x1E1E2E, panel: 0x16171B, line: 0x26272D, sel: 0x1F2230, ink: 0xE6E6EA, mute: 0x909199, orch: 0x5AA9FF, lane: 0xA3AAFF, wf: 0x5CC8C8, ok: 0x4CD27A, warn: 0xF2B04C, cap: 0x181825, hover: 0x222232, split: 0x3A3B4E, field: 0x24253A, faint: 0x6C7086, accent: 0x89B4FA, bad: 0xF38BA8)
    static let light = ChromePalette(windowBg: 0xFFFFFF, panel: 0xF3F4F6, line: 0xD5D8DE, sel: 0xE1E6F2, ink: 0x1F2328, mute: 0x565C66, orch: 0x0A5FC4, lane: 0x4A4FC7, wf: 0x0B6E74, ok: 0x17692F, warn: 0x8A5300, cap: 0xF3F3F3, hover: 0xF0F0ED, split: 0xDFDFDF, field: 0xF2F2EF, faint: 0x63666B, accent: 0x0963CE, bad: 0xC7212C)
}

extension TerminalTheme {
    static let fallbackDark: (bg: UInt32, fg: UInt32) = (0x1E1E2E, 0xCDD6F4)
    static let fallbackLight: (bg: UInt32, fg: UInt32) = (0xFFFFFF, 0x3A3A38)
}

enum ShellShadow {
    static let base: UInt32 = 0x000000
}

enum ShellType {
    static let sectionLabel: CGFloat = 10.5
    static let sectionTracking: CGFloat = 0.4
    static let rowTitle: CGFloat = 12.5
    static let rowTrailing: CGFloat = 10.5
    static let glyph: CGFloat = 10
    static let caption: CGFloat = 11.5
    static let small: CGFloat = 12.5
    static let body: CGFloat = 14
    static let code: CGFloat = 12.5
    static let terminal: CGFloat = 13.5
    static let switcherQuery: CGFloat = 16
    static let switcherRow: CGFloat = 13
    static let switcherMeta: CGFloat = 11
    static let detailTracking: CGFloat = 0.8
    static let chatH1: CGFloat = 19
    static let chatH2: CGFloat = 16.5
    static let chatH3: CGFloat = 14.5
    static let size18: CGFloat = 18
    static let size12: CGFloat = 12
    static let size9: CGFloat = 9
    static let size8: CGFloat = 8
    static let size8_5: CGFloat = 8.5
    static let size12_5: CGFloat = 12.5
    static let factoryTitle: CGFloat = 18
    static let factoryBody: CGFloat = 12
    static let factorySection: CGFloat = 13
    static let factoryDetail: CGFloat = 11
}

enum ShellSpace {
    static let detailWidth: CGFloat = 340
    static let detailPadding: CGFloat = 12
    static let detailGap: CGFloat = 14
    static let detailSectionGap: CGFloat = 4
    static let detailLineGap: CGFloat = 6
    static let detailHostPadX: CGFloat = 5
    static let detailHostPadY: CGFloat = 1
    static let sidebarWidth: CGFloat = 300
    static let rowHeight: CGFloat = 23
    static let rowPadX: CGFloat = 4
    static let paneCapHeight: CGFloat = 36
    static let chatColumn: CGFloat = 760
    static let chatGutter: CGFloat = 28
    static let chatItemGap: CGFloat = 18
    static let chatBlockGap: CGFloat = 12
    static let toolRow: CGFloat = 22
    static let docWidth: CGFloat = 420
    static let docMinWidth: CGFloat = 320
    static let switcherWidth: CGFloat = 560
    static let terminalPadX: CGFloat = 8
    static let terminalPadY: CGFloat = 6
    static let sidebarRowInset: CGFloat = 4
    static let sidebarAreaInset: CGFloat = 6
    static let sidebarIndent: CGFloat = 16
    static let paneCapGap: CGFloat = 8
    static let step10: CGFloat = 10
    static let step2: CGFloat = 2
    static let step5: CGFloat = 5
    static let step20: CGFloat = 20
    static let step3: CGFloat = 3
    static let step14: CGFloat = 14
    static let step16: CGFloat = 16
    static let step52: CGFloat = 52
    static let step7: CGFloat = 7
    static let step9: CGFloat = 9
    static let step24: CGFloat = 24
    static let step2_5: CGFloat = 2.5
    static let step11: CGFloat = 11
    static let step8: CGFloat = 8
    static let step4: CGFloat = 4
    static let step55: CGFloat = 55
    static let step12: CGFloat = 12
    static let step96: CGFloat = 96
    static let step32: CGFloat = 32
    static let step6: CGFloat = 6
    static let step15: CGFloat = 15
    static let step400: CGFloat = 400
    static let step13: CGFloat = 13
    static let step84: CGFloat = 84
    static let step116: CGFloat = 116
    static let step180: CGFloat = 180
    static let step1half: CGFloat = 1.5
    static let step148: CGFloat = 148
    static let step150: CGFloat = 150
    static let step320: CGFloat = 320
    static let step28: CGFloat = 28
    static let step22: CGFloat = 22
    static let step18: CGFloat = 18
    static let sidebarRowGap: CGFloat = 5
    static let switcherRowHeight: CGFloat = 32
    static let switcherQueryHeight: CGFloat = 46
    static let switcherQueryGap: CGFloat = 8
    static let switcherInset: CGFloat = 12
    static let chatBubbleX: CGFloat = 14
    static let chatBubbleY: CGFloat = 9
    static let chatComposerX: CGFloat = 14
    static let chatComposerTop: CGFloat = 12
    static let chatComposerBottom: CGFloat = 10
    static let factoryPadding: CGFloat = 20
    static let factoryGap: CGFloat = 22
    static let factoryRowGap: CGFloat = 8
    static let factoryDetailGap: CGFloat = 4
    static let factoryBarWidth: CGFloat = 140
    static let factoryLabelWidth: CGFloat = 22
}

enum ShellRadius {
    static let detailButton: CGFloat = 5
    static let row: CGFloat = 4
    static let control: CGFloat = 6
    static let code: CGFloat = 8
    static let overlay: CGFloat = 10
    static let composer: CGFloat = 14
    static let bubble: CGFloat = 16
    static let curve5: CGFloat = 5
    static let curve0_5: CGFloat = 0.5
    static let curve1_5: CGFloat = 1.5
    static let curve7: CGFloat = 7
}

enum ShellMotion {
    static let dragThresholdPx: CGFloat = 4
    static let tabEdgePx: CGFloat = 12
    static let edgeBandMin: CGFloat = 24
    static let edgeBandFraction: CGFloat = 0.25
    static let edgeBandMaxFraction: CGFloat = 0.33
    static let springLoadMs: CGFloat = 450
    static let zoneMorphMs: CGFloat = 140
    static let settleMs: CGFloat = 200
    static let cancelMs: CGFloat = 160
    static let fadeMs: CGFloat = 120
    static let reducedFadeMs: CGFloat = 100
    static let springResponse: CGFloat = 0.28
    static let springDampingFraction: CGFloat = 0.92
    static let zoneFillAlphaDark: CGFloat = 0.16
    static let zoneFillAlphaLight: CGFloat = 0.12
    static let zoneStroke: CGFloat = 1.5
    static let zoneInset: CGFloat = 4
    static let liftOpacity: CGFloat = 0.55
    static let chipOffset: CGFloat = 12
    static let ease: [CGFloat] = [0.2, 0, 0, 1]
}

enum ShellFace {
    static let size: CGFloat = 16
    static let dot: CGFloat = 6
    static let dotGap: CGFloat = 1.5
    static let dotOffset: CGFloat = 1
    static let ring: CGFloat = 0.5
    static let initial: CGFloat = 9.5
    static let tintOpacityLight: CGFloat = 0.24
    static let tintOpacityDark: CGFloat = 0.32
    static let tints: [UInt32] = [0x8B5E3C, 0xE8483F, 0xF08A24, 0xF0B429, 0x3ECF8E, 0x2FBFA0, 0x3B93F0, 0x8B5CF6, 0xE152B0]
}
