// Generated by shell/gen_tokens.py from shell/tokens.json. Do not edit; edit the JSON and rerun.
import type { ITheme } from "@xterm/xterm";

export type TokenMode = "light" | "dark";

/** The default Ghostty theme pair the Mac shell loads, as xterm themes. */
export const terminalThemes: Record<TokenMode, ITheme> = {
  dark: { background: "#1E1E2E", foreground: "#CDD6F4", cursor: "#F5E0DC", cursorAccent: "#1E1E2E", selectionBackground: "#585B70", selectionForeground: "#CDD6F4", black: "#45475A", red: "#F38BA8", green: "#A6E3A1", yellow: "#F9E2AF", blue: "#89B4FA", magenta: "#F5C2E7", cyan: "#94E2D5", white: "#A6ADC8", brightBlack: "#585B70", brightRed: "#F37799", brightGreen: "#89D88B", brightYellow: "#EBD391", brightBlue: "#74A8FC", brightMagenta: "#F2AEDE", brightCyan: "#6BD7CA", brightWhite: "#BAC2DE" },
  light: { background: "#FFFFFF", foreground: "#3A3A38", cursor: "#0969DA", cursorAccent: "#FFFFFF", selectionBackground: "#DBE5F1", selectionForeground: "#1F2328", black: "#24292F", red: "#CF222E", green: "#116329", yellow: "#7D4E00", blue: "#0969DA", magenta: "#8250DF", cyan: "#1B7C83", white: "#6E7781", brightBlack: "#57606A", brightRed: "#A40E26", brightGreen: "#1A7F37", brightYellow: "#633C01", brightBlue: "#218BFF", brightMagenta: "#A475F9", brightCyan: "#3192AA", brightWhite: "#8C959F" },
};

export const terminalFont = { family: "\"Cascadia Mono\", Consolas, monospace", size: 13.5 };

export const motion = {
  dragThresholdPx: 4,
  tabEdgePx: 12,
  edgeBandMin: 24,
  edgeBandFraction: 0.25,
  edgeBandMaxFraction: 0.33,
  springLoadMs: 450,
  zoneMorphMs: 140,
  settleMs: 200,
  cancelMs: 160,
  fadeMs: 120,
  reducedFadeMs: 100,
  springResponse: 0.28,
  springDampingFraction: 0.92,
  zoneFillAlphaDark: 0.16,
  zoneFillAlphaLight: 0.12,
  zoneStroke: 1.5,
  zoneInset: 4,
  liftOpacity: 0.55,
  chipOffset: 12,
  ease: [0.2, 0, 0, 1],
} as const;
